version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pim-backend-app
    ports:
      - '3000:3000'
    env_file:
      - .env.prod
    volumes:
      - ./serviceAccountKey.json:/app/serviceAccountKey.json
    restart: unless-stopped
    networks:
      - pim-network
  mongo:
    image: mongo:latest
    container_name: pim-mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: b3a3a467428f8f37710b23
      MONGO_INITDB_ROOT_PASSWORD: dc356e29a8ba6dddabbbfe
      MONGO_INITDB_DATABASE: pim
    volumes:
      - mongo_data:/data/db
    networks:
      - pim-network

volumes:
  mongo_data:

networks:
  pim-network:
    driver: bridge
