name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSHpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Run remote commands via SSH
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SERVER_IP << 'EOF'
            echo "Killing old dev server..."
            kill -9 $(ps aux | grep 'npm run start:dev' | grep -v grep | awk '{print $2}') $(lsof -t -i :3000) || true
            echo "Pulling latest code..."
            cd /path/to/your/app
            git pull origin main
            echo "Starting dev server..."
            nohup npm run start:dev > out.log 2>&1 &
          EOF
